### PR TITLE
Fail the postinstall script if compiling fails

### LINKED ISSUE #72: Install should fail if the binary doesn't work
`lib/install.js` catches any install/compilation error and logs the message, but doesn't actually fail the install. It probably needs to re-raise the exception, so that `yarn install` or `npm install` fail if the system is configured incorrectly.

### PR DESCRIPTION
**Pull request by evanj**
If the pngquant binary does not work and the compile fails, npm should
fail the package installation, since it will not work. Previously it
would log an error, but return exit code 0 so npm would think the
package was installed correctly. This will make it easier for users to
figure out why pngquant isn't working.

---

 Fixes #72

### CODE REVIEW

**Comment by vitia** [comment]
Please test mom install pngquant-bin on node:alpine or centos:7. It fails on both, though it does work on node:8.11.2.
